"""Initial

Revision ID: e701230aade1
Revises: 
Create Date: 2025-12-10 15:24:34.836421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e701230aade1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracking_code', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipments_id'), 'shipments', ['id'], unique=False)
    op.create_index(op.f('ix_shipments_tracking_code'), 'shipments', ['tracking_code'], unique=True)
    op.create_table('shipment_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('status_code', sa.String(length=50), nullable=False),
    sa.Column('status_text', sa.Text(), nullable=False),
    sa.Column('status_datetime', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipment_statuses_id'), 'shipment_statuses', ['id'], unique=False)
    op.create_index(op.f('ix_shipment_statuses_shipment_id'), 'shipment_statuses', ['shipment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shipment_statuses_shipment_id'), table_name='shipment_statuses')
    op.drop_index(op.f('ix_shipment_statuses_id'), table_name='shipment_statuses')
    op.drop_table('shipment_statuses')
    op.drop_index(op.f('ix_shipments_tracking_code'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_id'), table_name='shipments')
    op.drop_table('shipments')
    # ### end Alembic commands ###
